### ISSUE TITLE
Problem with Multiple menu

### ISSUE THREAD

**Issue by fujianto** [meanthemes/meanMenu#26]
Hello,
I'm trying to use this plugin on 2 menus in the same page. For some unknown reason, it's not working as I expected. Only the second menu content shown. here's my code.

```
jQuery(document).ready(function () {
    jQuery('.main-menu').meanmenu({
      meanMenuContainer: '.mobile-main-menu',
      meanScreenWidth: "959" ,
      meanRevealPosition: "left"
    });

    jQuery('.secondary-menu').meanmenu({
      meanMenuContainer: '.mobile-secondary-menu',
      meanScreenWidth: "959" ,
      meanRevealPosition: "left"
    });
});
```

Is it the correct way to do that?  Thanks.

**Comment by aktaruzzamancse** [comment]
It is Great solution. It works nice.

**Comment by mdemaree99** [comment]
Do you have a sample of how to get this to work?
Seems one menu will cover up both.
