### ISSUE TITLE
Parent href without link

### ISSUE THREAD

**Issue by mhulse** [meanthemes/meanMenu#48]
Hi,

Cool plugin, thanks for sharing!

### Quesion(s):

I'd like to have the ability to have parent hrefs not have links.

As it stands currently, only the `.mean-expand` class allows for open/close links. This creates odd UX if the link itself goes nowhere.

Is there a way to make the link clickable for expansion (like `.mean-expand`)?

Is the assumption that every parent list item’ href would go to a location?

Any thoughts on building in an option for this? What about an api function to trigger sub-list expansion?

Thanks!

**Comment by anyway** [comment]
Hi,

wonderful plugin, thank you very much for sharing!

I need this function also very urgent (Parent href without link). Can you please post a code snippet for your script? This is not working, when jquery.meanmenu.js is active:

$ ('a') click (function (event) {.
    event.preventDefault ();
    $ ('not-click > a');
});

Possibly not the best UX experience, I know, but absolutely necessary for my project.

Please help! Thanks a lot!

**Comment by meanthemes** [comment]
Hi @anyway I'm not quite sure what or who you are asking on this? This is a closed ticket and it isn't something we are adding to meanmenu. If you need it, you'll need to either use another plugin or figure out a solution yourself.

**Comment by anyway** [comment]
Thank you for your kind reply, and sorry, I just thought someone can help me with a hint or something. I came over Google to this thread and I'm not firm with the behavior on github. Sorry if I did something undesirable.

**Comment by meanthemes** [comment]
No problem at all, what I'll do is reopen the issue so its a bit more visible for anyone looking at the plugin. It is not something we are going to help on as we've already stated it's a bad UX from our point of view. However, @mhulse may have implemented his own solution so he may be able to offer some advice.

**Comment by mhulse** [comment]
Rather than fight the plugin, I decided to go with the flow by giving my top-level link a landing page URL.

I'm still not sure if having a clickable link and a + makes total sense. I suppose it's all in how you design your menu. For example, I did not make the + icons look like big buttons:

![screen shot 2015-02-12 at 1 07 01 pm](https://cloud.githubusercontent.com/assets/218624/6177010/20b33a1e-b2b8-11e4-857d-e8e91152e421.png)

In hindsight, I probably should have designed the + to look separate from the link itself (like the default styling of meanMenu) … then it would make more sense for the list item to have a link and the + would be clickable to expand open sub-items.

Anyway, sorry if that's of no help.

**Comment by anyway** [comment]
Thank you for reopen the issue @meanthemes .
@mhulse I unfortunately cannot create landing pages at this level in the navigation tree, otherwise I would do it instantly, but thank you for taking the time!

**Comment by Marak** [comment]
I was able to achieve this functionality using some simple jQuery.

Modify the header link to look like `<a href="#" class="meanLink">my link</a>`.

Then add this code on document ready.

``` js
          $('.meanLink').on('click', function(){
            var childExpands = $('.mean-expand', $(this).parent());
            childExpands[childExpands.length-1].click();
            return false;
          });
```

**Comment by Marak** [comment]
Ended up just choosing to use actual links on the section headers instead of making them hashtags.
