### ISSUE TITLE
Html definition in meanExpand option

### ISSUE THREAD

**Issue by daimoonis** [meanthemes/meanMenu#49]
Hi,

thanks for this cool plugin.

I have got a problem with "meanExpand" option of meanmenu. Im trying to setup fontawesome to plus/minus links etc. When i set meanExpand as html and click plus, then click minus, html definition apears as text.

My definition:
.meanmenu({
	meanMenuOpen: "&lt;i class=\"fa fa-bars\"&gt;&lt;/i&gt;",
	meanMenuClose: "&lt;i class=\"fa fa-close\">&lt;/i&gt;",
	meanExpand: "&lt;i class=\"fa fa-plus\">&lt;/i&gt;"
});

Its probably because of meanmenus js definition on line 193:
192: if (jQuery(this).hasClass("mean-clicked")) {
193: jQuery(this).text(meanExpand);

I know that in the documentation is: 
meanExpand: "+", // single character you want to represent the expand for ULs.

My opinion is it could be like this (as benefit), couldnot it? : 
193: jQuery(this).html(meanExpand);

This applies too to meanContract option.

**Comment by meanthemes** [comment]
That's a good suggestion, have you tried this and does it work? If it does, we'll have a look at ramifications and if all looks good, include it in the next release.

**Comment by daimoonis** [comment]
Yes it does work for me. You can find the working, changed version at odbory.info website.

All modifications are as follows (on meanMenu v2.0.8):

193: jQuery(this).html(meanExpand);
196: jQuery(this).html(meanContract);

**Comment by meanthemes** [comment]
Lovely thanks, we'll run a few tests this end and update, thanks for the suggestion :)

**Comment by BlueSky1021** [comment]
great advice,

It was a nice idea and i love it how it works now..
