### ISSUE TITLE
Doesn't work on some pages within the same website

### ISSUE THREAD

**Issue by eaglejohn** [meanthemes/meanMenu#50]
I have this weird problem that meanMenu works on and off on my website on a mobile phone (testing on iPhone). On the desktop meanMenu works on every page.

It works on http://www.concertatsea.nl/line-up/

It doesn't work on http://www.concertatsea.nl/info/info-veelgestelde-vragen/. When I check the element inspector (Safari + iOS Simulator) I see that the "mean-bar" div doesn't show up and the regular navigation keeps visible.

Any suggestions?

**Comment by meanthemes** [comment]
I can't see meanmenu on the page anywhere. If you have included it in other JS, I'd advise separating it back out along with the CSS to see if you have the same issue, if you do then we can isolate the issue more easily.

**Comment by eaglejohn** [comment]
Weird that you can't see the meanMenu at all.
I just disabled the cache plugin that I'm using, maybe that's causing that you're not seeing the menu at all. Can you check again please?

**Comment by meanthemes** [comment]
No I mean I cannot see a link to jquery.meanmenu.js in the code and I still can't. Is your JS bundled together? If so, please separate it out as I advised above.

**Comment by eaglejohn** [comment]
I hope you can see the meanMenu now? I just separated meanMenu from my bundled JS-file, although I always bundle my JS including meanMenu :-)

**Comment by meanthemes** [comment]
It is possibly because of the styling on your sub-menu nav. Try removing all class names via 

    meanRemoveAttrs: true

**Comment by eaglejohn** [comment]
I tried but it doesn't help. Other pages with sub-menu navigation, like http://www.concertatsea.nl/line-up/vrijdag/ are working fine. Just to be sure; on the pages it doesn't work the div "mean-bar" isn't showing up at all.

**Comment by meanthemes** [comment]
Hi there, well I can't see anything obvious. You're going to need to debug this one yourself and report back with the issue I'm afraid. I've not come across this issue before. Here is what I'd do if I had full access (probably clone the site first)...

1. Remove all other JS apart from meanmenu
2. Remove all CSS apart from meanmenu
3. See if meanmenu works
4. If it still fails, send me a link and I'll check it out
5. If it works, start adding in JS one by one until it breaks
6. Let me know which JS is causing the issue
7. If it still works after all JS...
8. Add CSS in bit by bit and see if it fails.
9. Let me know what CSS breaks it.

Hopefully you'll find the route cause with the above.

**Comment by eaglejohn** [comment]
I duplicated the website and tried step 1, 2 and 3 and meanMenu still doesn't show up on particular pages. Please check:

Doesn't work, "mean-bar" isn't showing on http://31.186.174.198/~casdup/info/info-veelgestelde-vragen/
Works, "mean-bar" is showing on http://31.186.174.198/~casdup/line-up/vrijdag/

To be sure again; on my desktop everything is fine, on my iPhone 5 (incognito, cleared cache) and iPhone simulator (with content reset) weird things happen.

**Comment by meanthemes** [comment]
This line is causing a JS error on that page

    <script>$(document).ready(function(){$('head').append('<meta http-equiv="refresh" content="10; url=http://31.186.174.198/~casdup/" />');});</script>

**Comment by eaglejohn** [comment]
Somehow you hit the 404 page which had a little JS on it. I removed that, just to be sure, but the issue is still there.

**Comment by eaglejohn** [comment]
Any news on this one? :-)

**Comment by meanthemes** [comment]
No sorry no news, I've been out of the office.

You're going to carry on debugging it I'm afraid.

There is something strange going on on the pages with issues on iPhones... I don't think its meanmenu related either. I'm seeing a zoomed out version on those pages with an issue on iPhone but the working ones are zoomed in. I usually use the viewport tag

    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">

The one you are using is probably going to cause some issues anyway - especially accessibility ones. That would probably be my next guess, to update that.

**Comment by eaglejohn** [comment]
Changing the meta viewport seems to be the solution!

**Comment by meanthemes** [comment]
lovely, I'll close this down then :)
