### ISSUE TITLE
Feature/ Enhancement: meanRemoveAttrs should include inline styles

### ISSUE THREAD

**Issue by Bryce-Mullican** [meanthemes/meanMenu#52]
Love meanMenu. I had a recent project that required me to remove the inline styles because the origin menu was using a slider effect that was applying inline styles to the nav elements. For my needs I just added it to the meanRemoveAttrs section, but I could see it as a separate option. Just a thought. Thanks again for the great work.

**Comment by meanthemes** [comment]
Thanks @Bryce-Mullican if you could share what you did exactly and we'll see if we can add another option?

**Comment by bryce-mullican** [comment]
Around line 162 below "jQuery(this).removeAttr("id");" I simply added "jQuery(this).removeAttr("style");"
