### ISSUE TITLE
Several menus on page

### ISSUE THREAD

**Issue by iryska** [meanthemes/meanMenu#54]
Hi Guys,

I was tried to use your plugin on site. I need 2 menus - header and footer.
With one menu per page it's work awesome.
But don't work when I try use it twice per page

code:
```javascript
jQuery(document).ready(function () {
    $('footer nav').meanmenu({ 
        meanMenuContainer: '#footer-responsive-nav',
        meanScreenWidth: '767'
    });
    $('header nav').meanmenu({
        meanMenuContainer: '#header-responsive-nav',
        meanScreenWidth: '767'
    });
});
```
it's add mean-bar to the footer twice - so I have 3 mean-bar on page
and it's not open/close it properly

**Comment by meanthemes** [comment]
You can only use it on one menu per page, we'll make that clearer in the readme.
