### ISSUE TITLE
Links on same page do not close meanmenu

### ISSUE THREAD

**Issue by shaneonabike** [meanthemes/meanMenu#57]
We had a need to create a meanmenu which links to pages on the same page (kind of like using a table of contents) since the page is quite long.

When clicking on a link the page does shift down to the appropriate place but unfortunately the mean menu does not close...

Just wondering if anyone has an idea of what I could do to fix that?

**Comment by meanthemes** [comment]
Hey there, check out the readme...

https://github.com/meanthemes/meanMenu/blob/master/README.md

> onePage: false 
> set to true for one page sites, the navigation will close back up on itself on click

**Comment by shaneonabike** [comment]
This is one of those moments when I slap my head and say thank you and sorry for asking an obvious question without thoroughly reviewing the docs.!!

**Comment by meanthemes** [comment]
We all do it, don't worry about it!
