### ISSUE TITLE
Menu Sliding Issue on an iPhone

### ISSUE THREAD

**Issue by fahidjavid** [meanthemes/meanMenu#58]
Hi!

When we navigation MeanMenu on an iPhone (Safari browser) it doesn't work smoothly. In first attempt we need to click twice to slide it down. It also doesn't slide up and down smoothly.

Regards,

Fahid

**Comment by meanthemes** [comment]
Hi @fahidjavid - no problems here on latest iOS on iPhone 6 using the demo. Is this a specific link issue or are you getting it on the demo too? If so, which iOS, which iPhone?

**Comment by fahidjavid** [comment]
Thanks for getting back to me. Kindly check on this site: http://inspirythemesdemo.com/medicalpress/

**Comment by fahidjavid** [comment]
However, I just checked MeanMenu demo site and it's working fine for me. Do you think we are doing something wrong? That causes the issue?

**Comment by meanthemes** [comment]
Hi @fahidjavid yes you are probably doing something wrong if it works on the demo and not your website. First, try disabling all CSS apart from meanmenu CSS. Then try disabling all JavaScript apart from jquery library and meanmenu.js.

**Comment by fahidjavid** [comment]
Thanks you so much for your help. I am consulting it with our Front-end developer now.

**Comment by meanthemes** [comment]
No problem, I'll close this down for now, but please re-open if you need more assistance

**Comment by mitcheal** [comment]
I'm having the same issue, any updates on this?

**Comment by mitcheal** [comment]
Corrected the issue with inspiry theme,  updated to the newest CSS from gethub

**Comment by fahidjavid** [comment]
Hi @mitcheal,

Thanks for sharing this solution!

Regards,

Fahid
