### ISSUE TITLE
Formatting issue on menu close

### ISSUE THREAD

**Issue by brigdev** [meanthemes/meanMenu#64]
Forcing "text-align: center" on closing the menu is causing a problem with the formatting of the menu button. I'm adding the word menu before the three bars. Forcing centered text means I have to make the button wider than it needs to be.

thank you.

**Comment by meanthemes** [comment]
Hi @brigdev - I'd suggest using some explicit CSS with an !important declaration as MeanMenu does not cater for text next to the hamburger icon.

**Comment by brigdev** [comment]
Thank you, @meanthemes. Have done that already. My suggestion was made in the hope of limiting the use of !important, but I appreciate that you don't cater for this situation.
