### ISSUE TITLE
browser crash in mobile devices

### ISSUE THREAD

**Issue by musharrafkhan** [meanthemes/meanMenu#67]
whenever i try to expand meanmenu browser crashes, i tested it in almost every browser

**Comment by meanthemes** [comment]
I'm not getting that here, what link are you testing?

**Comment by musharrafkhan** [comment]
whenever i open menu in mobile click any link it crashes every time my menu have over 30+ links with subs

**Comment by meanthemes** [comment]
wow that sounds like a crazy amount of links. As MeanMenu is written purely in jQuery I suspect that the browsers are having trouble rendering all of the content on the fly and hitting some kind of CPU issue. This isn't something we're going to investigate though as its an edge case and I'm sure there are plenty of other mobile menu options out there for you to try.
