### ISSUE TITLE
Live Demo

### ISSUE THREAD

**Issue by krzysko** [meanthemes/meanMenu#69]
Hi,

Please fix demo site... jquery is not loaded.

**Comment by meanthemes** [comment]
Hi @krzysko its working fine for me in Chrome, but we have recently switched the site over to SSL so I've updated the jQuery load so it is protocol-less instead. Thanks for letting me know!

**Comment by Kimmich-DigitalMedia** [comment]
Excuse my ignorance guys, but why doesn't the demo showing up the "submenu-tree" on the first top-level link (above 480px)? Or do I miss here something?

Cheers

Thomas

**Comment by Kimmich-DigitalMedia** [comment]
Yep I saw - it doesn't do (use superfish)! 

No chance you add it to the default?

Cheers

Thomas

**Comment by meanthemes** [comment]
Hi Thomas, sorry for the delayed response. This is not a menu system replacement. It is simply a lightweight piece of jQuery to convert a standard navigation into a mobile/tablet navigation.
